spring:
  application:
    name: backend
    # DB Setting
  datasource:
    url: jdbc:mysql://localhost:3306/baocard?serverTimezone=Asia/Seoul&useUniCode=yes&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${MYSQL_ROOT_PASSWORD}
    jpa:
      properties:
        hibernate:
          ddl-auto: update
          show_sql: true
          format_sql: true

jwt:
  secret:
    key: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK

openai:
  model: gpt-3.5-turbo
  api:
    key: ${OPENAI_SECRET_KEY}
    url: https://api.openai.com/v1/chat/completions
